### ISSUE TITLE
Victor's Ablation Study exps

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/omnigan#189]
| Exp.  | Comet Link | Slurm JOBID | comet.tags            | gen.m.use_spade | gen.s.depth_dada_fusion | gen.s.depth_feat_fusion | partition | tasks | train.pseudo.tasks | output_path                                           |
| :---: | :--------- | :---------- | :-------------------- | :-------------- | :---------------------- | :---------------------- | :-------- | :---- | :----------------- | :---------------------------------------------------- |
|   0   | [0][0]     | 747235      | m                     | False           | False                   | False                   | unkilla.. | m     | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (13) |
|   1   | [1][1]     | 747236      | md                    | False           | False                   | False                   | main      | md    | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (14) |
|   2   | [2][2]     | 747237      | ms                    | False           | False                   | False                   | main      | ms    | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (15) |
|   3   | [3][3]     | 747238      | msd                   | False           | False                   | False                   | long      | msd   | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (16) |
|   4   | [4][4]     | 747239      | msd spade             | True            | False                   | False                   | long      | msd   | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (17) |
|   5   | [5][5]     | 747240      | msd dada              | False           | True                    | True                    | long      | msd   | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (18) |
|   6   | [6][6]     | 747241      | msd spade dada        | True            | True                    | True                    | long      | msd   | []                 | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (19) |
|   7   | [7][7]     | 747242      | msd pseudo            | False           | False                   | False                   | long      | msd   | ['m', 's', 'd']    | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (20) |
|   8   | [8][8]     | 747243      | msd spade pseudo      | True            | False                   | False                   | long      | msd   | ['m', 's', 'd']    | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (21) |
|   9   | [9][9]     | 747244      | msd dada pseudo       | False           | True                    | True                    | long      | msd   | ['m', 's', 'd']    | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (22) |
|  10   | [10][10]   | 747245      | msd spade dada pseudo | True            | True                    | True                    | long      | msd   | ['m', 's', 'd']    | /miniscratch/schmidtv/vicc/omnigan/runs/ablation (23) |

[0]: https://www.comet.ml/vict0rsch/omnigan/55f5b2b4d2674cc68750005acc570942
[1]: https://www.comet.ml/vict0rsch/omnigan/0df7beb2e6b5410fbb6d841ffea9f740
[2]: https://www.comet.ml/vict0rsch/omnigan/a1091723f6f345b1bd08f62d9e2316cf
[3]: https://www.comet.ml/vict0rsch/omnigan/a031488d0dac453ebfbaff128d397786
[4]: https://www.comet.ml/vict0rsch/omnigan/7fdc666ec7984a0eb9000bae6ceae57b
[5]: https://www.comet.ml/vict0rsch/omnigan/ce8f0ca55bf247358b4e7f464828b2a7
[6]: https://www.comet.ml/vict0rsch/omnigan/9c6d7855836f45ecada21a44fb8b6841
[7]: https://www.comet.ml/vict0rsch/omnigan/6408b9a3e50642d5b2d5668a8b94e239
[8]: https://www.comet.ml/vict0rsch/omnigan/d2f5c2a1443645219b563c957ac4dc9d
[9]: https://www.comet.ml/vict0rsch/omnigan/8472e29a43124590b7f27ee75fa99690
[10]: https://www.comet.ml/vict0rsch/omnigan/36d8e9eefc8e4e2cb4fc78131746cda4

**Comment by vict0rsch** [comment]
Exp file:

```yaml
partition:
  sample: sequential
  from: 
  - unkillable
  - main
  - main
  - long
  - long
  - long
  - long
cpus: 4
gres: "gpu:rtx8000:1"
mem: 24G
output: "/miniscratch/schmidtv/vicc/omnigan/logs/ablation/slurm-%j.out"
codeloc: "$HOME/ccai/github/omnigan"
conda: "conda activate omnienv && conda deactivate && conda activate omnienv"
modules: "module load anaconda/3"

n_search: -1

tasks: [m, s, d]
"output_path": "/miniscratch/schmidtv/vicc/omnigan/runs/ablation"
"args.config": "$HOME/ccai/github/omnigan/shared/trainer/defaults.yaml"
"data.loaders.num_workers": 4
"data.loaders.batch_size": 4

"args.comet_tags": [ablation]
"comet.tags":
  sample: sequential
  from:
  - ["m"]
  - ["md"]
  - ["ms"]
  - ["msd"]
  - ["msd_spade"]
  - ["msd", "dada"]
  - ["msd_spade", "dada"]
  
"train.epochs": 150
"train.save_n_epochs": 25
"train.pseudo.tasks":
  sample: sequential
  from:
  - [m]
  - [m, d]
  - [m, s]
  - [m, s, d]
  - [m, s, d]
  - [m, s, d]
  - [m, s, d]
"train.pseudo.epochs": 10
"train.kitti.pretrain": False

"gen.m.spade.cond_nc": 15
"gen.m.use_spade":
  sample: cartesian
  from:
  - False
  - False
  - False
  - False
  - True
  - False
  - True
"gen.deeplabv3.backbone": resnet
"gen.s.depth_feat_fusion":
  sample: sequential
  from:
  - False
  - False
  - False
  - False
  - False
  - True
  - True
"gen.s.depth_dada_fusion":
  sample: sequential
  from:
  - False
  - False
  - False
  - False
  - False
  - True
  - True

```
